attribute attr;

namespace com;

table Req {}
table Res {}

rpc_service Svc (attr) {
// <- keyword
//          ^ type
//               ^ attribute
    Method(Req): Res;
//  ^ function
//         ^ type
//               ^ type
    Method2(Req): Res (attr: 0x3);
//                     ^ attribute
//                           ^ number
    MethodQualified(com.Req): com.Res;
//  ^ function
//                  ^ type
//                      ^ type
//                            ^ type
//                                ^ type
}
