attribute key;
attribute priority;

enum Color: byte { Blue }
table Vec3 {}
union Any {}

table Monster (key: "attr") {
// <- keyword
//    ^ type
//             ^ attribute
//                  ^ string
  pos:Vec3;
//^field
//    ^ type
  mana:short = 150;
//^field
//     ^ type.builtin
//             ^ number
  hp:short = 100;
//^field
//   ^ type.builtin
//           ^ number
  name:string;
//^field
//     ^ type.builtin
  friendly:bool = false (deprecated, priority: 1);
//         ^ type.builtin
//                ^ boolean
//                       ^ attribute
//                                   ^ attribute
//                                             ^ number
  inventory:[ubyte];
//^field
//           ^ type.builtin
//          ^ punctuation.bracket
//                ^ punctuation.bracket
  color:Color = Blue;
//^field
//      ^ type
//              ^ variant
  test:Any;
//^field
//     ^ type
}
